determiner(a).
determiner(an).
determiner(the).
determiner(this).
determiner(that).
determiner(these).
determiner(those).
determiner(my).
determiner(your).
determiner(his).
determiner(her).
determiner(its).
determiner(our).
determiner(their).
determiner(each).
determiner(every).
determiner(some).
determiner(any).
determiner(no).
determiner(many).
determiner(much).
determiner(more).
determiner(most).
determiner(few).
determiner(fewer).
determiner(fewest).
determiner(least).
determiner(such).
determiner(what).
determiner(which).
determiner(whose).
